### PR TITLE
package structure, performance, TravisCI, Python 3

### PR DESCRIPTION
**Pull request by svenkreiss**
Hi @thehesiod and @qedus,

This PR gets this module working in Python 2 and 3. We would like to submit this to PyPI and maintain it in this fork `sidewalklabs/sphere`, but wanted to run this past you in case you had any objections. Thanks for your work in porting this to Python.
- simplified package structure
- performance improvements
- Python 3 updates for RegionCoverer
- continuous tests with TravisCI
- option to run tests with `cProfile`
- add original s2-geometry library for test references
- extended README; converted from `md` to `rst` for PyPI

### CODE REVIEW

**Comment by thehesiod** [comment]
I actually didn't do this port, it was done by https://github.com/qedus/sphere. I just turned it into a module.  Did you mean to merge this there (Although he hasn't taken my PR yet)?  I'd happily take this merge too though.

**Comment by svenkreiss** [comment]
Great, thanks. We'll wait to hear back from @qedus on this and if we don't hear from him in the next few days we go ahead and publish to PyPI.

**Comment by svenkreiss** [comment]
making sure this reaches the original author:
cc @jongillham, please see the messages above

**Comment by thehesiod** [comment]
you may want to open a PR against his repo

**Comment by jongillham** [comment]
Thanks for the heads up. I am glad you find it useful! Feel free to use the package as you want.

As in the README.md I regret calling the package `sphere` due to awkward namespace collisions that arise when implementing some of the functions and with hindsight would have preferred to mirror the original S2 package conventions. If you decide to develop the package further then I suggest changing the API in that direction. Having said that, it is great to see what you have done so far!

**Comment by svenkreiss** [comment]
Thanks @thehesiod and @jongillham. Your suggested API change is much appreciated.

**Pull request merged**
